// app/lib/bannedWords.ts

export const BANNED_WORDS_ARRAY = [
  "assfuck", "cuntfucker", "niggers", "niggerhole", "nigger", "balllicker", "nlgger", 
  "porchmonkey", "porch-monkey", "cunt", "asswhore", "fuck", "assjockey", "dothead", 
  "blacks", "cumqueen", "fatfucker", "jigaboo", "jiggabo", "nlggor", "snownigger", 
  "spearchucker", "timber-nigger", "shitnigger", "asslick", "shithead", "asshole", 
  "cuntlicker", "kunt", "spaghettinigger", "towel-head", "chernozhopy", "asslicker", 
  "bluegum", "twat", "abcd", "bitchslap", "bulldyke", "choad", "cumshot", "fatass", 
  "jigger", "kyke", "cumskin", "asscowboy", "assmuncher", "banging", "burrhead", 
  "camel-jockey", "coon", "crotchrot", "cumfest", "dicklicker", "fag", "fagot", 
  "felatio", "fatfuck", "goldenshower", "hore", "jackoff", "jigg", "jigga", 
  "jizjuice", "jizm", "jiz", "jizzim", "kumming", "kunilingus", "moolinyan", 
  "motherfucking", "motherfuckings", "phuk", "sheboon", "shitforbrains", "slanteye", 
  "spick", "fuuck", "antinigger", "aperest", "americoon", "abc", "aunt-jemima", 
  "anal", "asspirate", "addict", "bitch", "ass", "buddhahead", "chode", "phuking", 
  "phukking", "bastard", "bulldike", "dripdick", "assassination", "a-rab", "buckra", 
  "bootycall", "assholes", "cheesedick", "cooter", "cum", "cumquat", "cunnilingus", 
  "datnigga", "deepthroat", "dick", "dickforbrains", "dickbrain", "dickless", 
  "dike", "diddle", "dixiedyke", "eskimo", "fannyfucker", "fatso", "fckcum", 
  "golliwog", "goyim", "homobangers", "hooters", "indognesial", "indonesial", 
  "jijjiboo", "knockers", "kummer", "mothafucka", "mooncricket", "oven-dodger", 
  "peckerwood", "phuked", "piccaninny", "picaninny", "phuq", "polock", "poorwhitetrash", 
  "prick", "pu55y", "pshek", "slut", "jizzum", "cunteyed", "spic", "swamp-guinea", 
  "stupidfucker", "stupidfuck", "titfuck", "twinkie", "cock", "abeed", "analannie", 
  "asshore", "beaner", "bootlip", "burr-head", "buttfucker", "butt-fucker", 
  "uncle-tom", "cocksmoker", "africoon", "amerikkkunt", "antifaggot", "assklown", 
  "asspuppies", "blackman", "jism", "blumpkin", "retard", "gringo", "douchebag", 
  "piefke", "areola", "backdoorman", "abbie", "bigbutt", "buttface", "cumbubble", 
  "cumming", "dego", "dong", "doggystyle", "doggiestyle", "erection", "feces", 
  "goddamned", "gonzagas", "greaser", "greaseball", "handjob", "half-breed", 
  "horney", "jihad", "kumquat", "lebo", "moskal", "mountain-turk", "nofuckingway", 
  "orgies", "orgy", "pecker", "poontang", "poon", "polentone", "pu55i", "shitfuck", 
  "shiteater", "shitdick", "sluts", "slutt", "mangal", "hymie", "stiffy", "titfucker", 
  "twink", "asspacker", "barelylegal", "bozgor", "bumfuck", "butchdyke", "buttpirate", 
  "cameljockey", "carcamano", "chankoro", "choc-ice", "chug", "ciapaty", "cina", 
  "cocksucer", "crackwhore", "bougnoule", "unfuckable", "africoon-americoon", 
  "africoonia", "americunt", "apesault", "assburgers", "fucktardedness", "sheepfucker", 
  "wuhan-virus", "wetback", "aseng", "bumblefuck", "fastfuck", "itch", "nizzle", 
  "oriental", "cisgender", "ballsack", "penis", "zigabo", "bule", "breastman", 
  "bountybar", "bounty-bar", "bondage", "bombing", "bullshit", "asses", "cunilingus", 
  "cummer", "dicklick", "ejaculation", "faeces", "hoes", "idiot", "laowai", "leb", 
  "muff", "muffdive", "oreo", "orgasm", "orgasim", "osama", "peepshow", "petrol-sniffer", 
  "perv", "prickhead", "shitfit", "spermbag", "suckmytit", "suckmydick", "suckmyass", 
  "suckme", "suckdick", "yuon", "motherfucker", "groe", "ali baba", "retarded", 
  "assfucker", "assmunch", "assranger", "ayrab", "assclown", "buttfuck", "buttman", 
  "chink", "cocksucker", "cooly", "coon-ass", "crotchmonkey", "bohunk", "cockcowboy", 
  "cocksmith", "catfucker", "fucktardedly", "trans-testicle", "wigger", "whiskeydick", 
  "aboriginal", "asskisser", "whitelist", "latinx", "yambag", "boob", "clunge", "af", 
  "wokeness", "bitchez", "zhyd", "bellend", "arsehole", "tatas", "assassinate", 
  "boonga", "booby", "bullcrap", "defecate", "dhoti", "dope", "hobo", "bigass", 
  "hussy", "illegal", "moneyshot", "molestor", "nooner", "nookie", "paleface", 
  "pansy", "peehole", "phonesex", "period", "pornking", "pornflick", "porn", 
  "pooper", "sexwhore", "shitface", "shit", "slav", "slimeball", "sniggers", 
  "snowback", "spermherder", "spankthemonkey", "spitter", "strapon", "tacohead", 
  "suckoff", "tranny", "bakra", "arabs", "arabush", "ashke-nazi", "assblaster", 
  "assmonkey", "badfuck", "bazongas", "beatoff", "bazooms", "balija", "bunghole", 
  "butchdike", "buttfuckers", "boche", "buttbang", "buttmunch", "charlie", "chav", 
  "chinaman", "coloured", "boong", "clit", "cockknob", "cocksucking", "cocktease", 
  "cokin", "cumsock", "fisting", "fuck-you", "fritzie", "transgendered", "whop", 
  "wtf", "vatnik", "assman", "gyopo", "goddam", "minge", "punani", "douche", 
  "doofus", "munter", "moron", "ballgag", "femsplaining", "asslover", "looney", 
  "boonga", "fat", "turd", "zhydovka", "effing", "minger", "dullard", "buggery", 
  "demon", "escort", "farting", "fairies", "husky", "incest", "hunky", "jiggy", 
  "laid", "molester", "mzungu", "pee-pee", "phungky", "porno", "pooping", 
  "prostitute", "pros", "sexslave", "sextogo", "shag", "shithappens", "shitfull", 
  "shitcan", "shinola", "slavedriver", "sleezeball", "swastika", "shits", "trots", 
  "trisexual", "twobitwhore", "munt", "gangsta", "abo", "analsex", "redskin", 
  "gypsy", "ape", "arab", "aravush", "armo", "arse", "assclown", "asswipe", 
  "beaney", "bigbastard", "bitches", "bogtrotter", "bung", "beaver", "bestial", 
  "bogan", "carpetmuncher", "carruth", "cocklover", "cockrider", "cornhole", 
  "bollock", "bog-irish", "chinamen", "clamdigger", "clamdiver", "dwarf", 
  "cakewalk", "ftw", "fml", "handicapped", "cawk", "norte", "troid", "willy", 
  "pud", "whitewashing", "brit"
];

export const BANNED_WORDS_SET = new Set(BANNED_WORDS_ARRAY);